# Generated by Django 5.1.5 on 2025-01-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('postal_code', models.CharField(max_length=15)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.department')),
            ],
        ),
    ]
