# Generated by Django 5.1.5 on 2025-01-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=70)),
                ('address_type', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=70)),
                ('address_numer', models.CharField(max_length=70)),
                ('references', models.TextField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.city')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('storage_capacity', models.IntegerField()),
                ('phone', models.CharField(max_length=60)),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.address')),
            ],
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=13)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=13)),
                ('profits', models.DecimalField(decimal_places=2, max_digits=13)),
                ('closing_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=100)),
                ('hiring_date', models.DateField()),
                ('position', models.CharField(max_length=60)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=13)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('installment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.installment')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=40)),
                ('hiring_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=13)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=13)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=13)),
                ('profits', models.DecimalField(decimal_places=2, max_digits=13)),
                ('month_closing', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.manager')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='crud.OrderProduct', to='crud.product'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(through='crud.ProductCategory', to='crud.product'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
            ],
        ),
        migrations.AddField(
            model_name='installment',
            name='purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.purchase'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.supplier'),
        ),
    ]
